# Generated by Django 3.2.6 on 2021-12-27 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='contact_date',
        ),
    ]
